/**
 * Enum of topics for kafka
 * @returns topics enum
 */
export enum ExternalTopic {
  USER_EVENT = 'EXTERNAL_KAFKA_TOPIC_USER_EVENT',
  USER_MIGRATE_EVENT = 'EXTERNAL_KAFKA_TOPIC_USER_MIGRATE_EVENT',
  USER_PHOTO_EVENT = 'EXTERNAL_KAFKA_TOPIC_USER_PHOTO_EVENT',
}
