export default () => ({
  KAFKA_BROKERS: process.env.KAFKA_BROKERS,
  KAFKA_CLIENT_ID: process.env.KAFKA_CLIENT_ID,
  KAFKA_USERNAME: process.env.KAFKA_USERNAME,
  KAFKA_PASSWORD: process.env.KAFKA_PASSWORD,
  KAFKA_TOPIC_SOCKER_USER_CONNECT: process.env.KAFKA_TOPIC_SOCKER_USER_CONNECT,
  KAFKA_TOPIC_SOCKER_MESSAGE_PAYLOAD_SEND:
    process.env.KAFKA_TOPIC_SOCKER_MESSAGE_PAYLOAD_SEND,
});
