export default () => ({
  redisUrl: process.env.REDISURL,
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
  REDIS_TTL: process.env.REDIS_TTL,
  KAFKA_BROKERS: process.env.KAFKA_BROKERS,
  KAFKA_CLIENT_ID: process.env.KAFKA_CLIENT_ID,
  KAFKA_USERNAME: process.env.KAFKA_USERNAME,
  KAFKA_PASSWORD: process.env.KAFKA_PASSWORD,
  KAFKA_TOPIC_SOCKER_USER_CONNECT: process.env.KAFKA_TOPIC_SOCKER_USER_CONNECT,
  KAFKA_TOPIC_SOCKER_MESSAGE_PAYLOAD_SEND:
    process.env.KAFKA_TOPIC_SOCKER_MESSAGE_PAYLOAD_SEND,
});
